// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipqyaabkauecrirwlwfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwcXlhYWJrYXVlY3Jpcndsd2ZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyNTY2MjMsImV4cCI6MjA1NTgzMjYyM30.P9q5oAkb4h-BWpdTpK20Vpdqras0cUhgHq9efDmxwas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);